---
- name: Add PHP 7.0 Repository
  apt_repository: repo="ppa:ondrej/php" state=present
  register: ppaPhp70Repoinstalled

- name: Install PHP 7
  apt: pkg={{ item }} state=latest
  when: ppaPhp70Repoinstalled|success
  with_items:
    - mcrypt
    - php7.0
    - php7.0-cli
    - php7.0-curl
    - php7.0-fpm
    - php7.0-gd
    - php7.0-imagick
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-mbstring
    - php7.0-dom


- name: Configure PHP
  template: src=php.ini.j2 dest=/etc/php/7.0/fpm/php.ini
  notify:
    - Reload PHP-FPM

- name: Enable MCRYPT
  shell: phpenmod mcrypt
  notify:
  - Reload PHP-FPM
