---
- name: Add PHP 5.6 Repository
  apt_repository: repo="ppa:ondrej/php5-5.6" state=present
  register: ppaphp56installed

- name: Install PHP
  apt: pkg={{ item }} state=latest 
  when: ppaphp56installed|success
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-mcrypt
    - php5-mysql
    - php5-sqlite
    - php5-xcache
    - php5-xmlrpc

- name: Configure PHP
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini
  notify:
    - Reload PHP-FPM

- name: Enable MCRYPT
  shell: php5enmod mcrypt
  notify:
  - Reload PHP-FPM
